version: '3.1'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=PalmPrintRecognitionSystemDB'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=sa'
    ports:
      - '5433:5432'
